// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: internal/grpc/taskpb/task.proto

package taskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_IN_PROGRESS Status = 1
	Status_STATUS_READY       Status = 2
	Status_STATUS_ERROR       Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_IN_PROGRESS",
		2: "STATUS_READY",
		3: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_IN_PROGRESS": 1,
		"STATUS_READY":       2,
		"STATUS_ERROR":       3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_taskpb_task_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_internal_grpc_taskpb_task_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_taskpb_task_proto_rawDescGZIP(), []int{0}
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputPath    string                 `protobuf:"bytes,1,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_internal_grpc_taskpb_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_taskpb_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_internal_grpc_taskpb_task_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *Result) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type TaskMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=task.v1.Status" json:"status,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessageRequest) Reset() {
	*x = TaskMessageRequest{}
	mi := &file_internal_grpc_taskpb_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessageRequest) ProtoMessage() {}

func (x *TaskMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_taskpb_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessageRequest.ProtoReflect.Descriptor instead.
func (*TaskMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_taskpb_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskMessageRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskMessageRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *TaskMessageRequest) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type TaskMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessageResponse) Reset() {
	*x = TaskMessageResponse{}
	mi := &file_internal_grpc_taskpb_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessageResponse) ProtoMessage() {}

func (x *TaskMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_taskpb_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessageResponse.ProtoReflect.Descriptor instead.
func (*TaskMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_taskpb_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_grpc_taskpb_task_proto protoreflect.FileDescriptor

const file_internal_grpc_taskpb_task_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/grpc/taskpb/task.proto\x12\atask.v1\"F\n" +
	"\x06Result\x12\x1f\n" +
	"\voutput_path\x18\x01 \x01(\tR\n" +
	"outputPath\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\x7f\n" +
	"\x12TaskMessageRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.task.v1.StatusR\x06status\x12'\n" +
	"\x06result\x18\x03 \x01(\v2\x0f.task.v1.ResultR\x06result\"/\n" +
	"\x13TaskMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\\\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STATUS_IN_PROGRESS\x10\x01\x12\x10\n" +
	"\fSTATUS_READY\x10\x02\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x032^\n" +
	"\vTaskService\x12O\n" +
	"\x10CommitTaskResult\x12\x1b.task.v1.TaskMessageRequest\x1a\x1c.task.v1.TaskMessageResponse\"\x00BCZAgithub.com/ibra172/go-ffmpeg-pipeline/internal/grpc/taskpb;taskpbb\x06proto3"

var (
	file_internal_grpc_taskpb_task_proto_rawDescOnce sync.Once
	file_internal_grpc_taskpb_task_proto_rawDescData []byte
)

func file_internal_grpc_taskpb_task_proto_rawDescGZIP() []byte {
	file_internal_grpc_taskpb_task_proto_rawDescOnce.Do(func() {
		file_internal_grpc_taskpb_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_taskpb_task_proto_rawDesc), len(file_internal_grpc_taskpb_task_proto_rawDesc)))
	})
	return file_internal_grpc_taskpb_task_proto_rawDescData
}

var file_internal_grpc_taskpb_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_taskpb_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_grpc_taskpb_task_proto_goTypes = []any{
	(Status)(0),                 // 0: task.v1.Status
	(*Result)(nil),              // 1: task.v1.Result
	(*TaskMessageRequest)(nil),  // 2: task.v1.TaskMessageRequest
	(*TaskMessageResponse)(nil), // 3: task.v1.TaskMessageResponse
}
var file_internal_grpc_taskpb_task_proto_depIdxs = []int32{
	0, // 0: task.v1.TaskMessageRequest.status:type_name -> task.v1.Status
	1, // 1: task.v1.TaskMessageRequest.result:type_name -> task.v1.Result
	2, // 2: task.v1.TaskService.CommitTaskResult:input_type -> task.v1.TaskMessageRequest
	3, // 3: task.v1.TaskService.CommitTaskResult:output_type -> task.v1.TaskMessageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_taskpb_task_proto_init() }
func file_internal_grpc_taskpb_task_proto_init() {
	if File_internal_grpc_taskpb_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_taskpb_task_proto_rawDesc), len(file_internal_grpc_taskpb_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_taskpb_task_proto_goTypes,
		DependencyIndexes: file_internal_grpc_taskpb_task_proto_depIdxs,
		EnumInfos:         file_internal_grpc_taskpb_task_proto_enumTypes,
		MessageInfos:      file_internal_grpc_taskpb_task_proto_msgTypes,
	}.Build()
	File_internal_grpc_taskpb_task_proto = out.File
	file_internal_grpc_taskpb_task_proto_goTypes = nil
	file_internal_grpc_taskpb_task_proto_depIdxs = nil
}
