// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/result/{id}": {
            "get": {
                "description": "Returns the processing result for a task when it is finished. For failed tasks, the API returns the error message instead of the output artifact.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "Get task result",
                "parameters": [
                    {
                        "type": "string",
                        "example": "123e4567-e89b-12d3-a456-426614174000",
                        "description": "Task ID in UUID format",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task finished successfully",
                        "schema": {
                            "$ref": "#/definitions/task.TaskResultResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/status/{id}": {
            "get": {
                "description": "Returns the current processing state of a task. The public status values are in_progress, ready, and error.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "Get task status",
                "parameters": [
                    {
                        "type": "string",
                        "example": "123e4567-e89b-12d3-a456-426614174000",
                        "description": "Task ID in UUID format",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Current task status",
                        "schema": {
                            "$ref": "#/definitions/task.TaskStatusResponse"
                        }
                    },
                    "202": {
                        "description": "Task is still processing",
                        "schema": {
                            "$ref": "#/definitions/task.TaskStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task": {
            "post": {
                "description": "Creates a new media-processing job. The task is queued immediately and can be checked by its UUID through the status and result endpoints.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "Create processing task",
                "parameters": [
                    {
                        "description": "Task creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/task.TaskPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Task created successfully",
                        "schema": {
                            "$ref": "#/definitions/task.CreateTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "task.CreateTaskResponse": {
            "type": "object",
            "properties": {
                "task_id": {
                    "description": "TaskID is the generated UUID of the created task.",
                    "type": "string"
                }
            }
        },
        "task.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error holds a public error message.",
                    "type": "string"
                }
            }
        },
        "task.TaskPayload": {
            "type": "object",
            "properties": {
                "operation": {
                    "description": "Operation defines the type of job to run. Examples: transcode, thumbnail, watermark.",
                    "type": "string"
                },
                "resolution": {
                    "description": "Resolution is used by transcode tasks and matches dimension presets such as 720p.",
                    "type": "string"
                },
                "target_format": {
                    "description": "TargetFormat is used by transcode tasks and may be set to mp4, mov, etc.",
                    "type": "string"
                }
            }
        },
        "task.TaskResult": {
            "type": "object",
            "properties": {
                "output_path": {
                    "description": "OutputPath is the resulting artifact path.",
                    "type": "string"
                }
            }
        },
        "task.TaskResultResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "description": "Result contains the processing output.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/task.TaskResult"
                        }
                    ]
                }
            }
        },
        "task.TaskStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status can be in_progress, ready, or error.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Media Pipeline App API",
	Description:      "API Server for a Multimedia Processor Application using FFmpeg",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
